### PR TITLE
Generate go file that represent VersionInfo struct

### PR DESCRIPTION
**Pull request by linquize**
`go generate` a `.go` file from `versioninfo.json`.

This allows the program to get version info from a global variable. For example, when starting the program, it prints the program name, version and copyright from a global variable.
This is also useful in non-Windows platforms too.
Every time when preparing a program release, the developer only need to update `versioninfo.json`.

### CODE REVIEW

**Comment by linquize** [comment]
test coverage increased

**Comment by msays2000** [comment]
Will this be checked in anytime soon :) or should we work with a fork of this code.

**Comment by linquize** [comment]
@msays2000 Oh,  you have just forked the project and merged me code.

**Comment by msays2000** [comment]
yes, I was testing to see if the PR will work to generate the versionInfo.go file. It does but in forked branch we have to change the import paths. 

I think many will just like a short format rather than a full deserialized struct object may be a small method to return the semantic version.   

const Version = "x.x.x.x"

**Comment by msays2000** [comment]
btw, I have deleted my fork after testing.

**Comment by josephspurrier** [comment]
I need to test this locally - let me see if I can get to it this weekend. Sorry for the delay.

**Comment by josephspurrier** [comment]
Thanks for adding in this functionality! I made it optional and changed the name of the parameters to be more descriptive.

**Pull request merged**
